import type { Metadata } from "next";
import { DM_Sans } from "next/font/google";
import "./globals.css";

import { TRPCProvider, TRPCReactProvider } from "@/trpc/client";
import { Toaster } from "@/components/ui/sonner";
const dm_sans = DM_Sans({
  subsets: ["latin"],
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={` ${dm_sans.className} antialiased`}
        suppressHydrationWarning
      >
        <TRPCReactProvider>
          {children} <Toaster />
        </TRPCReactProvider>
      </body>
    </html>
  );
}
